# Generated by Django 4.0.5 on 2022-08-27 18:16

from django.db import migrations, models
import djangojokes.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDFs only', storage=djangojokes.storage_backends.PrivateMediaStorage(), upload_to='resumes'),
        ),
    ]
